# Generated by Django 3.1.3 on 2021-01-12 15:10

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Client',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('email', models.EmailField(max_length=255, verbose_name='email')),
                ('repeat_type', models.CharField(blank=True, choices=[('None', 'None'), ('Daily', 'Daily'), ('Weekly', 'Weekly')], max_length=50, null=True)),
                ('shift', models.CharField(blank=True, choices=[('Morning', 'Morning')], max_length=50, null=True)),
                ('start_time', models.TimeField()),
                ('end_time', models.TimeField()),
                ('my_field', multiselectfield.db.fields.MultiSelectField(blank=True, choices=[(1, 'Mon'), (2, 'Tue'), (3, 'Wed'), (4, 'Thu'), (5, 'Fri'), (6, 'Sat'), (7, 'Sun')], max_length=13)),
                ('weekdays_only', models.BooleanField(blank=True, default=False)),
            ],
        ),
    ]
